### ISSUE TITLE
USER STORY: Navigation Bar

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/the-swede-restaurant#1]
EPIC: Navigation

As a **site user**, I can **easily find the navigation bar** so that **I can navigate the different pages of the website**. 

**Acceptance Criteria:**
- [x] The navigation bar should be located at the top of the screen with its items presented horizontally.
- [x] The navigation bar should take up less space on smaller screens (switch to hamburger menu).

**Tasks:**
- [x] Create a responsive navigation bar using bootstrap.
