### ISSUE TITLE
USER STORY: Social Media Links

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/the-swede-restaurant#10]
EPIC: Content

As a **site user** I can **find the restaurants social media links** so that **learn more about their business**. 

**Acceptance Criteria:**
- [x] The social media links should be available in the footer.
- [x] The link should be to Instagram and Facebook.
- [x] Each link should be represented by its relevant Font Awesome Icon. 

**Tasks:**
- [x] Create links to Instagram and Facebook in the footer and on the contact page.
- [x] Add Instagram and Facebook icons from Font Awesome.
