### ISSUE TITLE
USER STORY: Design

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/the-swede-restaurant#11]
EPIC: Content

As a **site user** I can **enjoy a clean and simple design** so that **it is not a distraction when looking for information**. 

**Acceptance Criteria:** 
- [x] The design should follow a nice color scheme without distracting backgrounds.
- [x] The fonts should work together.

**Tasks:**
- [x] Create the design based on the mockup.
- [x] Import Google Fonts that have been decided in the mockup.
