### ISSUE TITLE
USER STORY: Opening Hours

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/the-swede-restaurant#14]
EPIC: Content

As a **site user** I can **easily find the opening hours of the restaurant** so that **I know when it is possible to visit**. 

**Acceptance Criteria:** 
- [x] Opening hours should be available on the contact page.
- [x] The design should make it easy to locate on the page.

**Tasks:**
- [x] Create an information box on the contact page.
