### ISSUE TITLE
USER STORY: Create Account

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/the-swede-restaurant#15]
EPIC: Registration and Account Management

As a **site user** I can **create an account** so that **I can make, save, and manage my reservations**. 

**Acceptance Criteria:**
- [x] Signup/Login should be on its own page, and also linked on the "make reservations" page for unregistered users.
- [x] The user should be asked to create an account when wanting to make a reservation if they are not registered.
- [x] To create an account, the user should be asked to pick a username and a password.

**Tasks:**
- [x] Create a registration form using AllAuth.
- [x] Modify the design to fit the rest of the website.
