### ISSUE TITLE
USER STORY: Log in

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/the-swede-restaurant#16]
EPIC: Registration and Account Management

As a **registered user** I can **log in to my account** so that **I can access my information and reservations**. 

**Acceptance Criteria:**
- [x] The user can log in using username and password.
- [x] The design of the login page matches the rest of the website. 

**Tasks:**
- [x] Add login fields with required functionality using AllAuth.
- [x] Customize the design to fit the website.
