### ISSUE TITLE
USER STORY: Log Out

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/the-swede-restaurant#17]
EPIC: Registration and Account Management

As a **registered user** I can **log out from my account** so that **I can protect my personal information**. 

**Acceptance Criteria:**
- [x] The user should be able to log out by clicking a button.
- [x] The button should be easy to find. 

**Tasks:**
- [x] Add logout button with required functionality using AllAuth.
- [x] Customize the design to fit the website.
