### ISSUE TITLE
USER STORY: Logo Link

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/the-swede-restaurant#2]
EPIC: Navigation

As a **site user** I can **click the restaurant logo to get to the home page** so that **it is easy to navigate back if necessary**. 

**Acceptance Criteria:**
- [x] The logo should be clearly displayed in the top left corner at all times.
- [x]  When hovering over the logo, the mouse should change to a mouse/hand to indicate that it is a link.

**Tasks:**
- [x] Link the logo to the home page.
- [x] Create hovering effect using CSS/bootstrap.
