### ISSUE TITLE
USER STORY: Make Reservations

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/the-swede-restaurant#20]
EPIC: Reservations

As a **registered user** I can **make a reservation at the restaurant** so that **I can schedule a date and time to visit**. 

**Acceptance Criteria:**

Date and time:
- [x] For "make a reservation", there should be a calendar where the user can click what date and time they want to visit.
- [ ] The calendar should also show when the restaurant is fully booked (might not be implemented now).
- [ ] The user should not be able to book a date that has already passed or a time when the restaurant is not open. (Date restriction could not be implemented in time for submission).
- [x] The user should be able to pick a time slot from a list.

Number of guests:
- [x] The form should include field for numbers where the user can add the number of guests.

Add note:
- [x] The user should be able to add text in a text box with special requests or allergy information when making a reservation.

**Tasks:**
- [x] Create (customized) model.
- [x] Create form.
- [x] Add a calendar to the reservation form.
- [x] Implement field that only take numbers (make sure numbers can not be negative).
- [x] Add available time slots.
- [x] Create a textbox (restrict the number of characters).
