### ISSUE TITLE
USER STORY: View Reservations

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/the-swede-restaurant#21]
EPIC: Reservations

As a **registered user** I can **view my reservation(s)** so that **I can check the details**. 

**Acceptance Criteria:** 
- [x] The user should be able to show a list of the reservations they have made.
- [x] The list should contain date, time, number of guests, and potential notes. 

**Tasks:**
- [x] Create a Django model to store the data (also applies to creating the reservation form).
