### ISSUE TITLE
USER STORY: Manage Reservations

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/the-swede-restaurant#22]
EPIC: Reservations

As a **registered user** I can **manage my reservation(s) after its been saved** so that **I can keep the restaurant updated if something changes**. 

**Acceptance Criteria:** 
- [x] The user should be able to change date, time, number of guests and note after the initial reservation has been made.
- [ ] There should be a time limit for how close to the reservation the user can make changes. 48 hours as example (might not be implemented now). 

**Tasks:**
- [x] Make sure CRUD functionality is implemented with the help of Django.
