### ISSUE TITLE
USER STORY: Cancel Reservation

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/the-swede-restaurant#23]
EPIC: Reservations

As a **registered user** I can **cancel my reservation** so that **the date and time get available for other customers**. 

**Acceptance Criteria:** 
- [x] The user should have the option to cancel their reservation.
- [ ] Before canceling, an alert should pop up asking if the user is sure they want to cancel.

**Tasks:**
- [x] Make sure CRUD functionality is implemented with the help of Django.
