### ISSUE TITLE
USER STORY: Admin Panel

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/the-swede-restaurant#29]
EPIC: Reservations

As a **restaurant owner/site manager** I can **view reservations from an admin panel** so that **I can plan my business**. 

**Acceptance Criteria:** 
- [x] An admin should be able to log in and view the reservations that has been made.
- [x] An admin should be able to edit and delete bookings if necessary.

**Tasks:**
- [x] Create Django superuser
- [x] Register bookings app to admin index page
