### ISSUE TITLE
USER STORY: Find Menu

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/the-swede-restaurant#3]
EPIC: Navigation

As a **site user** I can **easily find the menu** so that **I can explore the food options**. 

**Acceptance Criteria:** 
- [x] A link to the menu should be a part of the navigation bar.
- [x] The menu should be displayed on its own page.

**Tasks:**
- [x] Create "menu" item in navbar linking to the menu page.
- [x]  Add font awesome icon.
