### ISSUE TITLE
USER STORY: Find Reservation Form

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/the-swede-restaurant#4]
EPIC: Navigation

As a **site user** I can **easily find where to make a reservation** so that **I can schedule when to visit the restaurant**. 

**Acceptance Criteria:** 
- [x] A link to the reservation form should be a part of the navbar. 
- [x] The reservation form should be displayed on its own page.

**Tasks:**
- [x] Create a "make reservation" item for the navbar linking to the page with the reservation form. 
- [x] Add font awesome icon.
