### ISSUE TITLE
USER STORY: Find Contact Details

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/the-swede-restaurant#5]
EPIC: Navigation

As a **site user** I can **find the contact information to the restaurant** so that **I know how to contact them if needed**. 

**Acceptance Criteria:** 
- [x] A link to the contact page should be a part of the navigation bar. 
- [x] Contact information should be displayed on its own page.
- [x] The contact information should contain phone number, email address, address, and opening hours. 

**Tasks:**
- [x] Create "contact" item in the navbar linking to the contact page. 
- [x] Add font awesome icon.
