### ISSUE TITLE
USER STORY: View Map

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/the-swede-restaurant#6]
EPIC: Content

As a **site user** I can **view the location of the restaurant on Google Maps** so that **I know where it is located**. 

**Acceptance Criteria:** 
- [ ] On the contact page, the user should be able to find the location of the restaurant on a Google Map. 
- [ ] The location should be pinned.

**Tasks:**
- [ ] Create section with Google Maps using API.
