### ISSUE TITLE
USER STORY: Home Page

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/the-swede-restaurant#7]
EPIC: Content

As a **site user** I can **get a clear first impression of what the site is about** so that **I can decide if I want to explore the website further**. 

**Acceptance Criteria:**
- [x] The landing page should contain a hero image relevant for a restaurant with Swedish food and "The Swede Restaurant" should be clearly visible.
- [x] There should be a link to "make reservation" on the landing page.
- [x] Below the hero image, there should be three sections linking to the most important information (menu, contact, make reservation). Their headings should be visible below the hero image. 

**Tasks:**
- [x] Add a hero image with text to the landing page using bootstrap.
- [x]  Create a button that takes the user to the "make reservation" form.
- [x] Create three sections below the hero image with links to their relevant page of information.
