### ISSUE TITLE
USER STORY: View Images of Food

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/the-swede-restaurant#9]
EPIC: Content

As a **site user** I can **view images of the food** so that **I know what it looks like**. 

**Acceptance Criteria:** 
- [ ] Images of the food should be available at the menu page.
- [ ] The images on the menu page should be presented in a visually pleasing way when it comes to size and positioning.

**Tasks:**
- [ ] Import relevant images from Pexels, Unsplash etc...
- [ ] Create table to display the images?
- [ ] Add responsiveness by showing fewer images on smaller screens. Use bootstrap.
